/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'main.exe'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 2 */
typedef unsigned __int64 ULONG_PTR;

/* 5 */
typedef unsigned int DWORD;

/* 4 */
struct _OVERLAPPED::$742A73540840F318F86F9CEE3D494648::$9BFE693EDA487769FDABADE5E43394F7
{
  DWORD Offset;
  DWORD OffsetHigh;
};

/* 6 */
typedef void *PVOID;

/* 3 */
union _OVERLAPPED::$742A73540840F318F86F9CEE3D494648
{
  struct
  {
    DWORD Offset;
    DWORD OffsetHigh;
  };
  PVOID Pointer;
};

/* 7 */
typedef void *HANDLE;

/* 1 */
struct _OVERLAPPED
{
  ULONG_PTR Internal;
  ULONG_PTR InternalHigh;
  union
  {
    struct
    {
      DWORD Offset;
      DWORD OffsetHigh;
    };
    PVOID Pointer;
  };
  HANDLE hEvent;
};

/* 8 */
struct __va_list_tag
{
  unsigned int gp_offset;
  unsigned int fp_offset;
  void *overflow_arg_area;
  void *reg_save_area;
};

/* 9 */
typedef __va_list_tag gcc_va_list[1];

/* 10 */
union __attribute__((aligned(16))) __m128i
{
  __int8 m128i_i8[16];
  __int16 m128i_i16[8];
  __int32 m128i_i32[4];
  __int64 m128i_i64[2];
  unsigned __int8 m128i_u8[16];
  unsigned __int16 m128i_u16[8];
  unsigned __int32 m128i_u32[4];
  unsigned __int64 m128i_u64[2];
};

